module.exports = {
  name: "enterprise-plugin",
  detectFile({ sourceFile }) {
    if (sourceFile.getFullText().includes("cy.loginAs")) {
      return [
        {
          pluginName: "enterprise-plugin",
          pattern: "cy.loginAs",
          message: "enterprise-plugin will translate loginAs into a Playwright-native bootstrap flow."
        }
      ];
    }

    return [];
  },
  translateCommand({ commandName, args, pageIdentifier }) {
    if (commandName === "loginAs") {
      return {
        code: `await ${pageIdentifier}.goto('/internal-login/' + ${args[0]});`
      };
    }

    return undefined;
  },
  postGenerate({ artifact }) {
    if (artifact.path.endsWith("items.spec.ts")) {
      return {
        ...artifact,
        content: `// post-generated by enterprise-plugin\n${artifact.content}`
      };
    }

    return artifact;
  }
};
