import { cp, mkdtemp, mkdir, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { runCli } from "../../src/cli";

const createdProjects: string[] = [];

async function createProjectFromFixture(fixtureName = "enterprise-suite"): Promise<string> {
  const targetRoot = await mkdtemp(path.join(os.tmpdir(), "cypw-"));
  const fixtureRoot = path.resolve(__dirname, "..", "fixtures", fixtureName);
  await cp(fixtureRoot, targetRoot, { recursive: true });
  createdProjects.push(targetRoot);
  return targetRoot;
}

afterEach(async () => {
  await Promise.allSettled(createdProjects.splice(0).map((projectRoot) => import("node:fs/promises").then(({ rm }) => rm(projectRoot, { recursive: true, force: true }))));
});

describe("cypw CLI", () => {
  it("initializes a config file in a greenfield project", async () => {
    const projectRoot = await mkdtemp(path.join(os.tmpdir(), "cypw-init-"));
    createdProjects.push(projectRoot);
    await runCli(["init", "--project-root", projectRoot]);

    const configPath = path.resolve(projectRoot, "cypw.config.jsonc");
    const raw = await readFile(configPath, "utf8");
    expect(raw).toContain(`"outputRoot": "playwright"`);
  });

  it("analyzes the enterprise fixture and emits readiness reporting", async () => {
    const projectRoot = await createProjectFromFixture();
    await runCli(["analyze", "--project-root", projectRoot]);

    const reportPath = path.resolve(projectRoot, ".cypw", "report.json");
    const report = JSON.parse(await readFile(reportPath, "utf8"));

    expect(report.readinessScore).toBeGreaterThan(0.7);
    expect(report.summary.totalFiles).toBeGreaterThanOrEqual(15);
    expect(report.hotspots.some((entry: { sourcePath: string }) => entry.sourcePath.endsWith("legacy.spec.ts"))).toBe(true);
    expect(report.controlFlowSummary.filesWithControlFlow).toBeGreaterThanOrEqual(4);
    expect(report.controlFlowSummary.strategyCounts.best_effort).toBeGreaterThanOrEqual(1);
  });

  it("converts the fixture suite, applies plugin hooks, and validates the generated output", async () => {
    const projectRoot = await createProjectFromFixture();
    await runCli(["convert", "--project-root", projectRoot]);

    const loginSpecPath = path.resolve(projectRoot, "playwright", "tests", "auth", "login.spec.ts");
    const itemsSpecPath = path.resolve(projectRoot, "playwright", "tests", "dashboard", "items.spec.ts");
    const scopedSpecPath = path.resolve(projectRoot, "playwright", "tests", "dashboard", "scoped.spec.ts");
    const aliasFlowSpecPath = path.resolve(projectRoot, "playwright", "tests", "dashboard", "alias-flow.spec.ts");
    const hookAliasSpecPath = path.resolve(projectRoot, "playwright", "tests", "dashboard", "hook-alias.spec.ts");
    const iterationSpecPath = path.resolve(projectRoot, "playwright", "tests", "dashboard", "iteration.spec.ts");
    const wrapValuesSpecPath = path.resolve(projectRoot, "playwright", "tests", "dashboard", "wrap-values.spec.ts");
    const pageObjectPath = path.resolve(projectRoot, "playwright", "page-objects", "login.page.ts");
    const handoffPath = path.resolve(projectRoot, ".cypw", "handoff.json");
    const reportPath = path.resolve(projectRoot, ".cypw", "report.json");

    const loginSpec = await readFile(loginSpecPath, "utf8");
    const itemsSpec = await readFile(itemsSpecPath, "utf8");
    const scopedSpec = await readFile(scopedSpecPath, "utf8");
    const aliasFlowSpec = await readFile(aliasFlowSpecPath, "utf8");
    const hookAliasSpec = await readFile(hookAliasSpecPath, "utf8");
    const iterationSpec = await readFile(iterationSpecPath, "utf8");
    const wrapValuesSpec = await readFile(wrapValuesSpecPath, "utf8");
    const pageObject = await readFile(pageObjectPath, "utf8");
    const handoff = JSON.parse(await readFile(handoffPath, "utf8"));
    const report = JSON.parse(await readFile(reportPath, "utf8"));

    expect(loginSpec).toContain("let loginPage: LoginPage;");
    expect(loginSpec).toContain("loginPage = new LoginPage(page);");
    expect(loginSpec).toContain("await goToDashboard(page);");
    expect(itemsSpec).toContain("// post-generated by enterprise-plugin");
    expect(itemsSpec).toContain("registerAlias(migrationState, \"getItems\"");
    expect(itemsSpec).toContain("await page.goto('/internal-login/' + \"manager\");");
    expect(scopedSpec).toContain("const scopeLocator");
    expect(scopedSpec).toContain("scopeLocator");
    expect(scopedSpec).not.toContain('mode: "serial"');
    expect(aliasFlowSpec).toContain("registerValueAlias(migrationState, \"user\"");
    expect(aliasFlowSpec).toContain("await getValueAlias(migrationState, \"user\")");
    expect(hookAliasSpec).toContain('test.describe.configure({ mode: "serial" });');
    expect(hookAliasSpec).toContain("let userData: any;");
    expect(hookAliasSpec).toContain("let primaryLink: any;");
    expect(hookAliasSpec).toContain("userData = await loadFixture");
    expect(hookAliasSpec).toContain("primaryLink = page.getByTestId");
    expect(hookAliasSpec).toContain("await page.getByTestId(\"username\").fill(userData.username);");
    expect(hookAliasSpec).toContain("await expect($link).toHaveAttribute(\"href\", \"/dashboard\");");
    expect(hookAliasSpec).toContain("await expect($link).toHaveClass(new RegExp(\"active\"));");
    expect(hookAliasSpec).toContain("await expect($link).toHaveText(\"Dashboard\");");
    expect(hookAliasSpec).toContain("// Preserve this comment during conversion.");
    expect(hookAliasSpec).not.toContain("this.userData");
    expect(iterationSpec).toContain("for (let index");
    expect(iterationSpec).toContain("registerValueAlias(migrationState, \"lastIndex\"");
    expect(wrapValuesSpec).toContain("const thenSubject");
    expect(wrapValuesSpec).toContain('const thenSubject1 = "manager";');
    expect(pageObject).toContain("return this.page.getByTestId");
    expect(handoff.some((entry: { sourcePath: string }) => entry.sourcePath.endsWith("legacy.spec.ts"))).toBe(true);
    expect(handoff.some((entry: { issues: Array<{ conversionStrategy?: string }> }) => entry.issues.some((issue) => issue.conversionStrategy === "manual_review"))).toBe(true);
    expect(report.files.some((entry: { sourcePath: string; issues: Array<{ aliasHoisted?: boolean; forcedSerialMode?: boolean }> }) => entry.sourcePath.endsWith("hook-alias.spec.ts") && entry.issues.some((issue) => issue.aliasHoisted && issue.forcedSerialMode))).toBe(true);
    expect(report.controlFlowSummary.upgradedFiles).toBeGreaterThanOrEqual(3);
    expect(report.validation.passed).toBe(true);
  });

  it("re-validates generated output and preserves manifest state", async () => {
    const projectRoot = await createProjectFromFixture();
    await runCli(["convert", "--project-root", projectRoot]);
    await runCli(["validate", "--project-root", projectRoot]);

    const manifestPath = path.resolve(projectRoot, ".cypw", "manifest.json");
    const reportPath = path.resolve(projectRoot, ".cypw", "report.json");
    const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
    const report = JSON.parse(await readFile(reportPath, "utf8"));

    expect(manifest.files.length).toBeGreaterThan(0);
    expect(report.validation.passed).toBe(true);
  });

  it("converts a JavaScript Cypress suite into compile-safe Playwright TypeScript", async () => {
    const projectRoot = await createProjectFromFixture("js-suite");
    await runCli(["convert", "--project-root", projectRoot]);

    const dynamicSpecPath = path.resolve(projectRoot, "playwright", "tests", "runtime", "dynamic.spec.ts");
    const spreadSpecPath = path.resolve(projectRoot, "playwright", "tests", "runtime", "spread-runtime.spec.ts");
    const pdfSpecPath = path.resolve(projectRoot, "playwright", "tests", "runtime", "pdf-compare.spec.ts");
    const helperPath = path.resolve(projectRoot, "playwright", "helpers", "commonjs-helper.ts");
    const shimPath = path.resolve(projectRoot, "playwright", "types", "external-modules.d.ts");
    const readmePath = path.resolve(projectRoot, "playwright", "README.md");
    const reportPath = path.resolve(projectRoot, ".cypw", "report.json");

    const dynamicSpec = await readFile(dynamicSpecPath, "utf8");
    const spreadSpec = await readFile(spreadSpecPath, "utf8");
    const pdfSpec = await readFile(pdfSpecPath, "utf8");
    const helperFile = await readFile(helperPath, "utf8");
    const shimFile = await readFile(shimPath, "utf8");
    const readme = await readFile(readmePath, "utf8");
    const report = JSON.parse(await readFile(reportPath, "utf8"));

    expect(dynamicSpec).toContain("let dynamicConfig: Record<string, any> = {};");
    expect(dynamicSpec).toContain("const localData: any = localDataImport;");
    expect(dynamicSpec).toContain("const mutableData: any = await loadProjectJson(\"cypress/fixtures/config.json\");");
    expect(dynamicSpec).toContain("await normalizeResponse(await request.get(\"/api/settings\"))");
    expect(dynamicSpec).toContain("expect(dynamicConfig.url).toBe(localData.baseUrl);");
    expect(spreadSpec).toContain("await page.evaluate(() => {");
    expect(spreadSpec).toContain("const appWindow: any = window as any;");
    expect(spreadSpec).toContain("return value;");
    expect(spreadSpec).toContain("expect(runtimeValue");
    expect(pdfSpec).toContain("import comparePdfImport from \"compare-pdf\";");
    expect(pdfSpec).toContain("const comparePdf: any = comparePdfImport;");
    expect(pdfSpec).toContain("const helpers: any = helpersImport;");
    expect(pdfSpec).toContain("let comparisonResults: any = await new comparePdf()");
    expect(pdfSpec).toContain("expect(comparisonResults.status).toBe(\"passed\");");
    expect(helperFile).toContain("export function getSettings()");
    expect(helperFile).toContain("export default __cypwDefaultExport;");
    expect(shimFile).toContain("declare module \"compare-pdf\";");
    expect(readme).toContain("compile-safe TypeScript fallbacks");
    expect(readme).toContain("compare-pdf");
    expect(report.files.every((entry: { outputPath: string }) => entry.outputPath.endsWith(".ts"))).toBe(true);
    expect(report.validation.passed).toBe(true);
  });
});
