import type { SupportFileIR } from "../ir/types";
import type { CompilerRuntime } from "../shared/runtime";
import type { FileAnalysis } from "../shared/types";

export function transformSupportFile(runtime: CompilerRuntime, sourcePath: string, analysis: FileAnalysis): SupportFileIR {
  const outputPath = runtime.pathResolution.sourceToOutput.get(sourcePath);
  if (!outputPath) {
    throw new Error(`No output path resolved for support file ${sourcePath}`);
  }

  const customCommands = Object.keys(analysis.commandUsages).filter((commandName) => ![
    "visit",
    "get",
    "find",
    "contains",
    "click",
    "type",
    "select",
    "check",
    "uncheck",
    "should",
    "intercept",
    "wait",
    "request",
    "fixture",
    "task",
    "as"
  ].includes(commandName));

  const content = `/**
 * Generated by cypw.
 * Support files are analyzed for custom commands and enterprise wrappers.
 * Review and port any Cypress-specific runtime setup manually.
 */

export const discoveredCustomCommands = ${JSON.stringify(customCommands, null, 2)} as const;
`;

  return {
    kind: "support",
    sourcePath,
    outputPath,
    content,
    issues: analysis.issues
  };
}
